version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - gocritic
    - revive
  settings:
    revive:
      severity: warning
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 100
  max-same-issues: 3
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
