package routes

import (
	"go_project/handlers"
	"go_project/logger"

	_ "go_project/docs" // docs are generated by swag.

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func RegisterRoutes(r *gin.Engine) {
	logger.Log.Info().Msg("Adding RegisterRoutes()")
	r.GET("/users", handlers.GetUsers)
	r.POST("/users", handlers.AddUser)

	// Swagger UI route
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	logger.Log.Info().Msg("Finished RegisterRoutes()")
}
